#!/usr/bin/env python3

from getopt import getopt
import sys

from common.dump import dump
from common.sync import sync

stuff = {
    "~/.config/{kitty,nvim,openbox,pipewire,tint2,zed}",
    "~/.themes",
    "~/.local/bin/{yarn}"
}

options, _ = getopt(sys.argv[1:], "ds", ["dump", "sync"])

for option, _ in options:
    if option in ("-d", "--dump"):
        dump(stuff)
        break

    if option in ("-s", "--sync"):
        sync(stuff)
        break

print("Usage: ./goog [-d | --dump] [-s | --sync]\n")
print("A simple tool for dumping dotfiles and syncing them")
exit(1)
